name: Cluster Name
description: Generates a cluster name

inputs:
  arch:
    required: false
    default: x86

runs:
  using: composite
  steps:
  - name: Install eksctl
    id: generated_name
    shell: bash
    run: |
      SHA_FULL="${{ github.sha }}"
      SHA_SHORT=${SHA_FULL:0:4}
      echo "NAME=${{ github.job }}-$SHA_SHORT-${{ inputs.arch }}" >> "$GITHUB_OUTPUT"

outputs:
  name:
    value: ${{ steps.generated_name.outputs.NAME }}
