name: Delete Cluster

inputs:
  cluster-name:
    required: true
  shutdown:
    required: false
    default: true
  AWS_ACCESS_KEY_ID:
    required: false
  AWS_SECRET_ACCESS_KEY:
    required: false

runs:
  using: composite
  steps:
  - if: inputs.platform == 'eks'
    shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    run: |
      if [[ ${{ inputs.shutdown }} == "true" ]]; then
        eksctl delete cluster --name ${{ steps.name.outputs.NAME }}
      fi
